/********************************************************************
* anawinds_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error anawinds_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableanawinds_dict();
extern void G__cpp_setup_inheritanceanawinds_dict();
extern void G__cpp_setup_typetableanawinds_dict();
extern void G__cpp_setup_memvaranawinds_dict();
extern void G__cpp_setup_globalanawinds_dict();
extern void G__cpp_setup_memfuncanawinds_dict();
extern void G__cpp_setup_funcanawinds_dict();
extern void G__set_cpp_environmentanawinds_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TArtWINDSPla.hh"
#include "include/TArtWINDSPlaPara.hh"
#include "include/TArtCalibWINDSPla.hh"
#include "include/TArtWINDSParameters.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anawinds_dictLN_TClass;
extern G__linked_taginfo G__anawinds_dictLN_TBuffer;
extern G__linked_taginfo G__anawinds_dictLN_TMemberInspector;
extern G__linked_taginfo G__anawinds_dictLN_TObject;
extern G__linked_taginfo G__anawinds_dictLN_TNamed;
extern G__linked_taginfo G__anawinds_dictLN_TString;
extern G__linked_taginfo G__anawinds_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anawinds_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anawinds_dictLN_TList;
extern G__linked_taginfo G__anawinds_dictLN_TClonesArray;
extern G__linked_taginfo G__anawinds_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__anawinds_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anawinds_dictLN_TArtDataObject;
extern G__linked_taginfo G__anawinds_dictLN_TArtWINDSPla;
extern G__linked_taginfo G__anawinds_dictLN_TArtRIDFMap;
extern G__linked_taginfo G__anawinds_dictLN_TArtWINDSPlaPara;
extern G__linked_taginfo G__anawinds_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anawinds_dictLN_TArtReconstruction;
extern G__linked_taginfo G__anawinds_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__anawinds_dictLN_TArtWINDSParameters;
extern G__linked_taginfo G__anawinds_dictLN_TArtStoreManager;
extern G__linked_taginfo G__anawinds_dictLN_TArtCalibWINDSPla;
extern G__linked_taginfo G__anawinds_dictLN_vectorlETArtWINDSPlaParamUcOallocatorlETArtWINDSPlaParamUgRsPgR;
extern G__linked_taginfo G__anawinds_dictLN_reverse_iteratorlEvectorlETArtWINDSPlaParamUcOallocatorlETArtWINDSPlaParamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anawinds_dictLN_TXMLNode;
extern G__linked_taginfo G__anawinds_dictLN_maplETArtRIDFMapcOTArtWINDSPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtWINDSPlaParamUgRsPgRsPgR;

/* STUB derived class for protected member access */
