//
// File generated by rootcint at Tue Dec 12 16:23:49 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME anashiki_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "anashiki_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

/********************************************************
* anashiki_dict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableanashiki_dict();

extern "C" void G__set_cpp_environmentanashiki_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/TArtMDF_Frag_Eloss_Emp.hh");
  G__add_compiledheader("include/TArtMDF_TOFSBTTgt_C.hh");
  G__add_compiledheader("include/TArtMDF_Beam_Eloss_C.hh");
  G__add_compiledheader("include/TArtShikiParameters.hh");
  G__add_compiledheader("include/TArtEasyGamma.hh");
  G__add_compiledheader("include/TArtEasyPID.hh");
  G__add_compiledheader("include/TArtMDF_TOFSBTTgt_Emp.hh");
  G__add_compiledheader("include/TArtMDF_Beam_Eloss_Emp.hh");
  G__add_compiledheader("include/TArtEasyNeutron.hh");
  G__add_compiledheader("include/TArtEasyMassExcess.hh");
  G__add_compiledheader("include/TArtMDF_s027_FlMDF.hh");
  G__add_compiledheader("include/TArtEasyEventMixing.hh");
  G__add_compiledheader("include/TArtEasyEnergyLossFunc.hh");
  G__add_compiledheader("include/TArtEasyNeutrons.hh");
  G__add_compiledheader("include/TArtEasyBeam.hh");
  G__add_compiledheader("include/TArtEasyTarget.hh");
  G__add_compiledheader("include/TArtMDF_s027_TofMDF.hh");
  G__add_compiledheader("include/TArtMDF_Frag_Eloss_C.hh");
  G__add_compiledheader("include/TArtEasySAMURAIPID.hh");
  G__add_compiledheader("include/TArtMDF_TOFSBTTgt_Pb.hh");
  G__add_compiledheader("include/TArtMDF_Beam_Eloss_Pb.hh");
  G__add_compiledheader("include/TArtEasyTimer.hh");
  G__add_compiledheader("include/TArtMDF_Frag_Eloss_Pb.hh");
  G__add_compiledheader("include/TArtMDF_s027_BrhoMDF.hh");
  G__add_compiledheader("include/TArtEasyScaler.hh");
  G__cpp_reset_tagtableanashiki_dict();
}
#include <new>
extern "C" int G__cpp_dllrevanashiki_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncanashiki_dict {
 public:
  G__Sizep2memfuncanashiki_dict(): p(&G__Sizep2memfuncanashiki_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncanashiki_dict::*p)();
};

size_t G__get_sizep2memfuncanashiki_dict()
{
  G__Sizep2memfuncanashiki_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceanashiki_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableanashiki_dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtEasyTarget*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtEasyTargetmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtEasyTargetmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtEasyTarget*,less<int> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtEasyTargetmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtEasyTargetmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<Int_t,Int_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_pairlEintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::pair<Int_t,Int_t>,Double_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<Int_t,Int_t>,Double_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<int,int>,double>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<int,int>,double,less<pair<int,int> > >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TLorentzVector>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TH1*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<std::pair<Int_t,Int_t>,TString>",117,G__get_linked_tagnum(&G__anashiki_dictLN_pairlEpairlEintcOintgRcOTStringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<pair<Int_t,Int_t>,TString>",117,G__get_linked_tagnum(&G__anashiki_dictLN_pairlEpairlEintcOintgRcOTStringgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::pair<std::pair<Int_t,Int_t>,TString>,std::vector<Double_t> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<pair<Int_t,Int_t>,TString>,std::vector<Double_t> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<pair<int,int>,TString>,vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<pair<pair<int,int>,TString>,vector<double,allocator<double> >,less<pair<pair<int,int>,TString> > >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtRawDataObject*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtRawFADCDataObject*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtRawTacquilaDataObject*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtRawSegmentObject*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtRawScalerObject*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,const TArtNEBULAPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,const TArtNEBULAPlaPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,const TArtHIMEPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtHIMEPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtHIMEPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,const TArtHIMEPlaPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtHIMEPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtHIMEPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,const TArtNEBULAHPCPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAHPCParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAHPCParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,const TArtNEBULAHPCPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAHPCParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAHPCParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtTacquilaMap,const TArtNeuLANDPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtTacquilaMap,const TArtNeuLANDPlaPara*,less<TArtTacquilaMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtTacquilaMap,const TArtTacquilaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtTacquilaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtTacquilaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtTacquilaMap,const TArtTacquilaPara*,less<TArtTacquilaMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtTacquilaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtTacquilaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtDCHitPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtDCHitParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDCHitParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtDCHitPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtDCHitParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDCHitParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtHODPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtHODPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtHODPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtHODPlaPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtHODPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtHODPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtRPTOFPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtRPTOFPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtRPTOFPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtRPTOFPlaPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtRPTOFPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtRPTOFPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtTEDCsIPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtTEDCsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtTEDCsIParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TArtRIDFMap,TArtTEDCsIPara*,less<TArtRIDFMap> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtTEDCsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtTEDCsIParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtNEBULAPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtNEBULAPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtNEBULAPlaPara*,less<int> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtNEBULAPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtHIMEPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtHIMEPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtHIMEPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtHIMEPlaPara*,less<int> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtHIMEPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtHIMEPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtNEBULAHPCPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtNEBULAHPCParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAHPCParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtNEBULAHPCPara*,less<int> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtNEBULAHPCParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAHPCParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtNeuLANDPlaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtNeuLANDPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNeuLANDPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtNeuLANDPlaPara*,less<int> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtNeuLANDPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNeuLANDPlaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtTacquilaPara*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtTacquilaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtTacquilaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,TArtTacquilaPara*,less<int> >",117,G__get_linked_tagnum(&G__anashiki_dictLN_maplEintcOTArtTacquilaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtTacquilaParamUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtEasyNeutron*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtDCHit*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TArtDCTrack*>",117,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__anashiki_dictLN_vectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */
extern "C" void G__cpp_setup_memvaranashiki_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/

/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncanashiki_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalanashiki_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {
}

static void G__cpp_setup_func30() {
}

static void G__cpp_setup_func31() {
}

static void G__cpp_setup_func32() {
}

static void G__cpp_setup_func33() {
}

static void G__cpp_setup_func34() {
}

static void G__cpp_setup_func35() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcanashiki_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
  G__cpp_setup_func30();
  G__cpp_setup_func31();
  G__cpp_setup_func32();
  G__cpp_setup_func33();
  G__cpp_setup_func34();
  G__cpp_setup_func35();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__anashiki_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__anashiki_dictLN_pairlEintcOintgR = { "pair<int,int>" , 115 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEintcOTArtEasyTargetmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtEasyTargetmUgRsPgRsPgR = { "map<int,TArtEasyTarget*,less<int>,allocator<pair<const int,TArtEasyTarget*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR = { "map<pair<int,int>,double,less<pair<int,int> >,allocator<pair<const pair<int,int>,double> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR = { "vector<TLorentzVector,allocator<TLorentzVector> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TLorentzVector,allocator<TLorentzVector> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR = { "vector<TH1*,allocator<TH1*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TH1*,allocator<TH1*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_pairlEpairlEintcOintgRcOTStringgR = { "pair<pair<int,int>,TString>" , 115 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR = { "map<pair<pair<int,int>,TString>,vector<double,allocator<double> >,less<pair<pair<int,int>,TString> >,allocator<pair<const pair<pair<int,int>,TString>,vector<double,allocator<double> > > > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR = { "vector<TArtRawDataObject*,allocator<TArtRawDataObject*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtRawDataObject*,allocator<TArtRawDataObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR = { "vector<TArtRawFADCDataObject*,allocator<TArtRawFADCDataObject*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtRawFADCDataObject*,allocator<TArtRawFADCDataObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgR = { "vector<TArtRawTacquilaDataObject*,allocator<TArtRawTacquilaDataObject*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtRawTacquilaDataObject*,allocator<TArtRawTacquilaDataObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR = { "vector<TArtRawSegmentObject*,allocator<TArtRawSegmentObject*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtRawSegmentObject*,allocator<TArtRawSegmentObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR = { "vector<TArtRawScalerObject*,allocator<TArtRawScalerObject*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtRawScalerObject*,allocator<TArtRawScalerObject*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAPlaParamUgRsPgRsPgR = { "map<TArtRIDFMap,const TArtNEBULAPlaPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,const TArtNEBULAPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtHIMEPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtHIMEPlaParamUgRsPgRsPgR = { "map<TArtRIDFMap,const TArtHIMEPlaPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,const TArtHIMEPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAHPCParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAHPCParamUgRsPgRsPgR = { "map<TArtRIDFMap,const TArtNEBULAHPCPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,const TArtNEBULAHPCPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUgRsPgRsPgR = { "map<TArtTacquilaMap,const TArtNeuLANDPlaPara*,less<TArtTacquilaMap>,allocator<pair<const TArtTacquilaMap,const TArtNeuLANDPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtTacquilaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtTacquilaParamUgRsPgRsPgR = { "map<TArtTacquilaMap,const TArtTacquilaPara*,less<TArtTacquilaMap>,allocator<pair<const TArtTacquilaMap,const TArtTacquilaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOTArtDCHitParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDCHitParamUgRsPgRsPgR = { "map<TArtRIDFMap,TArtDCHitPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,TArtDCHitPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOTArtHODPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtHODPlaParamUgRsPgRsPgR = { "map<TArtRIDFMap,TArtHODPlaPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,TArtHODPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOTArtRPTOFPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtRPTOFPlaParamUgRsPgRsPgR = { "map<TArtRIDFMap,TArtRPTOFPlaPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,TArtRPTOFPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplETArtRIDFMapcOTArtTEDCsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtTEDCsIParamUgRsPgRsPgR = { "map<TArtRIDFMap,TArtTEDCsIPara*,less<TArtRIDFMap>,allocator<pair<const TArtRIDFMap,TArtTEDCsIPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEintcOTArtNEBULAPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAPlaParamUgRsPgRsPgR = { "map<int,TArtNEBULAPlaPara*,less<int>,allocator<pair<const int,TArtNEBULAPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEintcOTArtHIMEPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtHIMEPlaParamUgRsPgRsPgR = { "map<int,TArtHIMEPlaPara*,less<int>,allocator<pair<const int,TArtHIMEPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEintcOTArtNEBULAHPCParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAHPCParamUgRsPgRsPgR = { "map<int,TArtNEBULAHPCPara*,less<int>,allocator<pair<const int,TArtNEBULAHPCPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEintcOTArtNeuLANDPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNeuLANDPlaParamUgRsPgRsPgR = { "map<int,TArtNeuLANDPlaPara*,less<int>,allocator<pair<const int,TArtNeuLANDPlaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_maplEintcOTArtTacquilaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtTacquilaParamUgRsPgRsPgR = { "map<int,TArtTacquilaPara*,less<int>,allocator<pair<const int,TArtTacquilaPara*> > >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgR = { "vector<TArtEasyNeutron*,allocator<TArtEasyNeutron*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtEasyNeutron*,allocator<TArtEasyNeutron*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgR = { "vector<TArtDCHit*,allocator<TArtDCHit*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtDCHit*,allocator<TArtDCHit*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_vectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgR = { "vector<TArtDCTrack*,allocator<TArtDCTrack*> >" , 99 , -1 };
G__linked_taginfo G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TArtDCTrack*,allocator<TArtDCTrack*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableanashiki_dict() {
  G__anashiki_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__anashiki_dictLN_pairlEintcOintgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEintcOTArtEasyTargetmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtEasyTargetmUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__anashiki_dictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__anashiki_dictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_pairlEpairlEintcOintgRcOTStringgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtHIMEPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtHIMEPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAHPCParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAHPCParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtTacquilaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtTacquilaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOTArtDCHitParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDCHitParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOTArtHODPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtHODPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOTArtRPTOFPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtRPTOFPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplETArtRIDFMapcOTArtTEDCsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtTEDCsIParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEintcOTArtNEBULAPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEintcOTArtHIMEPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtHIMEPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEintcOTArtNEBULAHPCParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAHPCParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEintcOTArtNeuLANDPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNeuLANDPlaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_maplEintcOTArtTacquilaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtTacquilaParamUgRsPgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__anashiki_dictLN_vectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgR.tagnum = -1 ;
  G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableanashiki_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_pairlEintcOintgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEintcOTArtEasyTargetmUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtEasyTargetmUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEpairlEintcOintgRcOdoublecOlesslEpairlEintcOintgRsPgRcOallocatorlEpairlEconstsPpairlEintcOintgRcOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETH1mUcOallocatorlETH1mUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETH1mUcOallocatorlETH1mUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_pairlEpairlEintcOintgRcOTStringgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRcOlesslEpairlEpairlEintcOintgRcOTStringgRsPgRcOallocatorlEpairlEconstsPpairlEpairlEintcOintgRcOTStringgRcOvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawDataObjectmUcOallocatorlETArtRawDataObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawFADCDataObjectmUcOallocatorlETArtRawFADCDataObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawTacquilaDataObjectmUcOallocatorlETArtRawTacquilaDataObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawSegmentObjectmUcOallocatorlETArtRawSegmentObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtRawScalerObjectmUcOallocatorlETArtRawScalerObjectmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtHIMEPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtHIMEPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOconstsPTArtNEBULAHPCParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOconstsPTArtNEBULAHPCParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtNeuLANDPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtTacquilaMapcOconstsPTArtTacquilaParamUcOlesslETArtTacquilaMapgRcOallocatorlEpairlEconstsPTArtTacquilaMapcOconstsPTArtTacquilaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtDCHitParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDCHitParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtHODPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtHODPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtRPTOFPlaParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtRPTOFPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplETArtRIDFMapcOTArtTEDCsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtTEDCsIParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEintcOTArtNEBULAPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEintcOTArtHIMEPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtHIMEPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEintcOTArtNEBULAHPCParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNEBULAHPCParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEintcOTArtNeuLANDPlaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtNeuLANDPlaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_maplEintcOTArtTacquilaParamUcOlesslEintgRcOallocatorlEpairlEconstsPintcOTArtTacquilaParamUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtEasyNeutronmUcOallocatorlETArtEasyNeutronmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCHitmUcOallocatorlETArtDCHitmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_vectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__anashiki_dictLN_reverse_iteratorlEvectorlETArtDCTrackmUcOallocatorlETArtDCTrackmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupanashiki_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupanashiki_dict()");
  G__set_cpp_environmentanashiki_dict();
  G__cpp_setup_tagtableanashiki_dict();

  G__cpp_setup_inheritanceanashiki_dict();

  G__cpp_setup_typetableanashiki_dict();

  G__cpp_setup_memvaranashiki_dict();

  G__cpp_setup_memfuncanashiki_dict();
  G__cpp_setup_globalanashiki_dict();
  G__cpp_setup_funcanashiki_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncanashiki_dict();
  return;
}
class G__cpp_setup_initanashiki_dict {
  public:
    G__cpp_setup_initanashiki_dict() { G__add_setup_func("anashiki_dict",(G__incsetup)(&G__cpp_setupanashiki_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initanashiki_dict() { G__remove_setup_func("anashiki_dict"); }
};
G__cpp_setup_initanashiki_dict G__cpp_setup_initializeranashiki_dict;

