/********************************************************************
* anacatana_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error anacatana_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableanacatana_dict();
extern void G__cpp_setup_inheritanceanacatana_dict();
extern void G__cpp_setup_typetableanacatana_dict();
extern void G__cpp_setup_memvaranacatana_dict();
extern void G__cpp_setup_globalanacatana_dict();
extern void G__cpp_setup_memfuncanacatana_dict();
extern void G__cpp_setup_funcanacatana_dict();
extern void G__set_cpp_environmentanacatana_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TArtCalibCATANA.hh"
#include "include/TArtCATANACsI.hh"
#include "include/TArtCATANACsIPara.hh"
#include "include/TArtCATANAParameters.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anacatana_dictLN_TClass;
extern G__linked_taginfo G__anacatana_dictLN_TBuffer;
extern G__linked_taginfo G__anacatana_dictLN_TMemberInspector;
extern G__linked_taginfo G__anacatana_dictLN_TObject;
extern G__linked_taginfo G__anacatana_dictLN_TNamed;
extern G__linked_taginfo G__anacatana_dictLN_TString;
extern G__linked_taginfo G__anacatana_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anacatana_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacatana_dictLN_TList;
extern G__linked_taginfo G__anacatana_dictLN_TClonesArray;
extern G__linked_taginfo G__anacatana_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__anacatana_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacatana_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anacatana_dictLN_TArtReconstruction;
extern G__linked_taginfo G__anacatana_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__anacatana_dictLN_TArtCATANACsIPara;
extern G__linked_taginfo G__anacatana_dictLN_TArtCATANAParameters;
extern G__linked_taginfo G__anacatana_dictLN_TArtCATANACsI;
extern G__linked_taginfo G__anacatana_dictLN_TArtStoreManager;
extern G__linked_taginfo G__anacatana_dictLN_TArtCalibCATANA;
extern G__linked_taginfo G__anacatana_dictLN_vectorlETArtCATANACsIParamUcOallocatorlETArtCATANACsIParamUgRsPgR;
extern G__linked_taginfo G__anacatana_dictLN_reverse_iteratorlEvectorlETArtCATANACsIParamUcOallocatorlETArtCATANACsIParamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anacatana_dictLN_TArtDataObject;
extern G__linked_taginfo G__anacatana_dictLN_TArtRIDFMap;
extern G__linked_taginfo G__anacatana_dictLN_TXMLNode;
extern G__linked_taginfo G__anacatana_dictLN_maplETArtRIDFMapcOTArtCATANACsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtCATANACsIParamUgRsPgRsPgR;
extern G__linked_taginfo G__anacatana_dictLN_maplETArtRIDFMapcOTArtCATANACsIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtCATANACsIParamUgRsPgRsPgRcLcLiterator;

/* STUB derived class for protected member access */
