/********************************************************************
* ananadeko_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ananadeko_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableananadeko_dict();
extern void G__cpp_setup_inheritanceananadeko_dict();
extern void G__cpp_setup_typetableananadeko_dict();
extern void G__cpp_setup_memvarananadeko_dict();
extern void G__cpp_setup_globalananadeko_dict();
extern void G__cpp_setup_memfuncananadeko_dict();
extern void G__cpp_setup_funcananadeko_dict();
extern void G__set_cpp_environmentananadeko_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TArtAlias.hh"
#include "include/TArtSimpleFunction.hh"
#include "include/TArtExec.hh"
#include "include/TArtObjLinkManager.hh"
#include "include/TArtCanvasManager.hh"
#include "include/TArtGlobal.hh"
#include "include/TArtHistManager.hh"
#include "include/TArtTreeManager.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ananadeko_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ananadeko_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ananadeko_dictLN_maplEunsignedsPintcOboolcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOboolgRsPgRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_maplEunsignedsPintcOunsignedsPintcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOunsignedsPintgRsPgRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ananadeko_dictLN_maplEunsignedsPintcOpairlEdoublecOdoublegRcOlesslEunsignedsPintgRcOallocatorlEpairlEconstsPunsignedsPintcOpairlEdoublecOdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__ananadeko_dictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__ananadeko_dictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__ananadeko_dictLN_TFitResultPtr;
extern G__linked_taginfo G__ananadeko_dictLN_TH1;
extern G__linked_taginfo G__ananadeko_dictLN_TGraph;
extern G__linked_taginfo G__ananadeko_dictLN_TGraphErrors;
extern G__linked_taginfo G__ananadeko_dictLN_TTree;

/* STUB derived class for protected member access */
