/********************************************************************
* anasilicons_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error anasilicons_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableanasilicons_dict();
extern void G__cpp_setup_inheritanceanasilicons_dict();
extern void G__cpp_setup_typetableanasilicons_dict();
extern void G__cpp_setup_memvaranasilicons_dict();
extern void G__cpp_setup_globalanasilicons_dict();
extern void G__cpp_setup_memfuncanasilicons_dict();
extern void G__cpp_setup_funcanasilicons_dict();
extern void G__set_cpp_environmentanasilicons_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TArtSILICONSParameters.hh"
#include "include/TArtSILICONSPara.hh"
#include "include/TArtCalibSILICONS.hh"
#include "include/TArtSILICONS.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anasilicons_dictLN_TClass;
extern G__linked_taginfo G__anasilicons_dictLN_TBuffer;
extern G__linked_taginfo G__anasilicons_dictLN_TMemberInspector;
extern G__linked_taginfo G__anasilicons_dictLN_TObject;
extern G__linked_taginfo G__anasilicons_dictLN_TNamed;
extern G__linked_taginfo G__anasilicons_dictLN_TString;
extern G__linked_taginfo G__anasilicons_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anasilicons_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anasilicons_dictLN_TList;
extern G__linked_taginfo G__anasilicons_dictLN_TClonesArray;
extern G__linked_taginfo G__anasilicons_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__anasilicons_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anasilicons_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anasilicons_dictLN_TXMLNode;
extern G__linked_taginfo G__anasilicons_dictLN_TArtSILICONSPara;
extern G__linked_taginfo G__anasilicons_dictLN_TArtRIDFMap;
extern G__linked_taginfo G__anasilicons_dictLN_TArtSILICONSParameters;
extern G__linked_taginfo G__anasilicons_dictLN_maplETArtRIDFMapcOTArtSILICONSParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtSILICONSParamUgRsPgRsPgR;
extern G__linked_taginfo G__anasilicons_dictLN_maplETArtRIDFMapcOTArtSILICONSParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtSILICONSParamUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__anasilicons_dictLN_TArtDataObject;
extern G__linked_taginfo G__anasilicons_dictLN_TArtSILICONS;
extern G__linked_taginfo G__anasilicons_dictLN_TArtSILICONSParacLcLDetDirection;
extern G__linked_taginfo G__anasilicons_dictLN_TArtReconstruction;
extern G__linked_taginfo G__anasilicons_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__anasilicons_dictLN_TArtStoreManager;
extern G__linked_taginfo G__anasilicons_dictLN_TArtCalibSILICONS;
extern G__linked_taginfo G__anasilicons_dictLN_vectorlETArtSILICONSParamUcOallocatorlETArtSILICONSParamUgRsPgR;
extern G__linked_taginfo G__anasilicons_dictLN_reverse_iteratorlEvectorlETArtSILICONSParamUcOallocatorlETArtSILICONSParamUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
