/********************************************************************
* anadali_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error anadali_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableanadali_dict();
extern void G__cpp_setup_inheritanceanadali_dict();
extern void G__cpp_setup_typetableanadali_dict();
extern void G__cpp_setup_memvaranadali_dict();
extern void G__cpp_setup_globalanadali_dict();
extern void G__cpp_setup_memfuncanadali_dict();
extern void G__cpp_setup_funcanadali_dict();
extern void G__set_cpp_environmentanadali_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TArtDALINaIPara.hh"
#include "include/TArtDALIParameters.hh"
#include "include/TArtCalibDALI.hh"
#include "include/TArtDALINaI.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anadali_dictLN_TClass;
extern G__linked_taginfo G__anadali_dictLN_TBuffer;
extern G__linked_taginfo G__anadali_dictLN_TMemberInspector;
extern G__linked_taginfo G__anadali_dictLN_TObject;
extern G__linked_taginfo G__anadali_dictLN_TNamed;
extern G__linked_taginfo G__anadali_dictLN_TString;
extern G__linked_taginfo G__anadali_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anadali_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anadali_dictLN_TList;
extern G__linked_taginfo G__anadali_dictLN_TClonesArray;
extern G__linked_taginfo G__anadali_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__anadali_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anadali_dictLN_TArtRIDFMap;
extern G__linked_taginfo G__anadali_dictLN_TArtDALINaIPara;
extern G__linked_taginfo G__anadali_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anadali_dictLN_TXMLNode;
extern G__linked_taginfo G__anadali_dictLN_TArtDALIParameters;
extern G__linked_taginfo G__anadali_dictLN_maplETArtRIDFMapcOTArtDALINaIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDALINaIParamUgRsPgRsPgR;
extern G__linked_taginfo G__anadali_dictLN_maplETArtRIDFMapcOTArtDALINaIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtDALINaIParamUgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__anadali_dictLN_TArtReconstruction;
extern G__linked_taginfo G__anadali_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__anadali_dictLN_TArtDALINaI;
extern G__linked_taginfo G__anadali_dictLN_TArtStoreManager;
extern G__linked_taginfo G__anadali_dictLN_TArtCalibDALI;
extern G__linked_taginfo G__anadali_dictLN_vectorlETArtDALINaIParamUcOallocatorlETArtDALINaIParamUgRsPgR;
extern G__linked_taginfo G__anadali_dictLN_reverse_iteratorlEvectorlETArtDALINaIParamUcOallocatorlETArtDALINaIParamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anadali_dictLN_TArtDataObject;

/* STUB derived class for protected member access */
