/********************************************************************
* anaespri_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error anaespri_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableanaespri_dict();
extern void G__cpp_setup_inheritanceanaespri_dict();
extern void G__cpp_setup_typetableanaespri_dict();
extern void G__cpp_setup_memvaranaespri_dict();
extern void G__cpp_setup_globalanaespri_dict();
extern void G__cpp_setup_memfuncanaespri_dict();
extern void G__cpp_setup_funcanaespri_dict();
extern void G__set_cpp_environmentanaespri_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/TArtRNaIPara.hh"
#include "include/TArtFADC.hh"
#include "include/TArtTDCHit.hh"
#include "include/TArtTDCHitPara.hh"
#include "include/TArtRDC.hh"
#include "include/TArtUserParameters.hh"
#include "include/TArtESPRIParameters.hh"
#include "include/TArtCalibBDC.hh"
#include "include/TArtCalibRDC.hh"
#include "include/TArtDia.hh"
#include "include/TArtBDC.hh"
#include "include/TArtCalibPlas.hh"
#include "include/TArtBLD.hh"
#include "include/TArtFADCPara.hh"
#include "include/TArtCalibFADC.hh"
#include "include/TArtCalibBLD.hh"
#include "include/TArtCalibDia.hh"
#include "include/TArtCalibRNaI.hh"
#include "include/TArtRNaI.hh"
#include "include/TArtCalibTDCHit.hh"
#include "include/TArtPlas.hh"
#include "include/TArtPlasPara.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__anaespri_dictLN_TClass;
extern G__linked_taginfo G__anaespri_dictLN_TBuffer;
extern G__linked_taginfo G__anaespri_dictLN_TMemberInspector;
extern G__linked_taginfo G__anaespri_dictLN_TObject;
extern G__linked_taginfo G__anaespri_dictLN_TNamed;
extern G__linked_taginfo G__anaespri_dictLN_TString;
extern G__linked_taginfo G__anaespri_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anaespri_dictLN_TList;
extern G__linked_taginfo G__anaespri_dictLN_TClonesArray;
extern G__linked_taginfo G__anaespri_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anaespri_dictLN_TArtRIDFMap;
extern G__linked_taginfo G__anaespri_dictLN_TArtRNaIPara;
extern G__linked_taginfo G__anaespri_dictLN_TArtDataObject;
extern G__linked_taginfo G__anaespri_dictLN_TArtFADC;
extern G__linked_taginfo G__anaespri_dictLN_TArtTDCHit;
extern G__linked_taginfo G__anaespri_dictLN_TArtTDCHitPara;
extern G__linked_taginfo G__anaespri_dictLN_TArtRDC;
extern G__linked_taginfo G__anaespri_dictLN_TXMLNode;
extern G__linked_taginfo G__anaespri_dictLN_TArtStoreManager;
extern G__linked_taginfo G__anaespri_dictLN_TArtUserParameters;
extern G__linked_taginfo G__anaespri_dictLN_maplETStringcOintcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOintgRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_maplETStringcOdoublecOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__anaespri_dictLN_TArtFADCPara;
extern G__linked_taginfo G__anaespri_dictLN_TArtPlasPara;
extern G__linked_taginfo G__anaespri_dictLN_TArtESPRIParameters;
extern G__linked_taginfo G__anaespri_dictLN_maplETArtRIDFMapcOTArtTDCHitParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtTDCHitParamUgRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_maplETArtRIDFMapcOTArtFADCParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtFADCParamUgRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_maplETArtRIDFMapcOTArtPlasParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtPlasParamUgRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_maplETArtRIDFMapcOTArtRNaIParamUcOlesslETArtRIDFMapgRcOallocatorlEpairlEconstsPTArtRIDFMapcOTArtRNaIParamUgRsPgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_TArtReconstruction;
extern G__linked_taginfo G__anaespri_dictLN_TArtBDC;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibBDC;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibRDC;
extern G__linked_taginfo G__anaespri_dictLN_TArtDia;
extern G__linked_taginfo G__anaespri_dictLN_TArtRawSegmentObject;
extern G__linked_taginfo G__anaespri_dictLN_TArtPlas;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibPlas;
extern G__linked_taginfo G__anaespri_dictLN_vectorlETArtPlasParamUcOallocatorlETArtPlasParamUgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_reverse_iteratorlEvectorlETArtPlasParamUcOallocatorlETArtPlasParamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anaespri_dictLN_TArtBLD;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibFADC;
extern G__linked_taginfo G__anaespri_dictLN_vectorlETArtFADCParamUcOallocatorlETArtFADCParamUgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_reverse_iteratorlEvectorlETArtFADCParamUcOallocatorlETArtFADCParamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibBLD;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibDia;
extern G__linked_taginfo G__anaespri_dictLN_TArtRNaI;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibRNaI;
extern G__linked_taginfo G__anaespri_dictLN_vectorlETArtRNaIParamUcOallocatorlETArtRNaIParamUgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_reverse_iteratorlEvectorlETArtRNaIParamUcOallocatorlETArtRNaIParamUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__anaespri_dictLN_TArtCalibTDCHit;
extern G__linked_taginfo G__anaespri_dictLN_vectorlETArtTDCHitParamUcOallocatorlETArtTDCHitParamUgRsPgR;
extern G__linked_taginfo G__anaespri_dictLN_reverse_iteratorlEvectorlETArtTDCHitParamUcOallocatorlETArtTDCHitParamUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
